### PR TITLE
4/23/18 Webinar Listing Changes

### PR DESCRIPTION
**Pull request by mackenzielyng**
Updates to webinar listing page made on 4/23.

### CODE REVIEW

**Comment by audrieMSFT** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@mackenzielyng : Thanks for your contribution! The author, @audrieMSFT, has been notified to review your proposed change.

**Comment by audrieMSFT** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@mackenzielyng : Thanks for your contribution! The author, @audrieMSFT, has been notified to review your proposed change.

**Comment by audrieMSFT** [comment]
#sign-off

**Comment by AFTOwen** [comment]
@audrieMSFT This content is already live. If we need a change, @mackenzielyng needs to create another PR.

**Comment by audrieMSFT** [comment]
ok just leave the typo then - it's not serious.

**Pull request merged**
