### PR TITLE
Update grid-onrecordselect.md

### PR DESCRIPTION
**Pull request by ericregnier**
Added a useful scenario when to use the OnRecordSelect event

### CODE REVIEW

**Comment by JimDaly** [comment]
@ericregnier 
Thanks.

I've asked @jasongre and some of the devs to review.
There are a few broken links. Figuring out the relative path can be tricky. 

You should be able to use something like this to create a relative URL within the microsoft.learn content. 

`[Power Apps grid control](/power-apps/maker/model-driven-apps/the-power-apps-grid-control)`

Just remove this part: `https://learn.microsoft.com/en-us`

**Comment by ericregnier** [comment]
@JimDaly I've been trying to resolve the relative paths of the URLs but having trouble. Do you have any idea? I did try simply removing the "https://learn.microsoft.com/en-us" and tried to add some "../"

**Comment by JimDaly** [comment]
> @JimDaly I've been trying to resolve the relative paths of the URLs but having trouble. Do you have any idea? I did try simply removing the "https://learn.microsoft.com/en-us" and tried to add some "../"

This should work:

`More information: [Power Apps grid control](../../../../../maker/model-driven-apps/the-power-apps-grid-control.md)`

**Review by JimDaly — CHANGES_REQUESTED** [review]
Can the JS function follow the guidance we have for naming? [Specifically to define a namespace?](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/walkthrough-write-your-first-client-script#detailed-code-explanation)

**Comment by ericregnier** [comment]
@JimDaly applied changes as suggested. I purposely did not reference the 2nd editable grid (Power Apps (legacy)) because it is legacy and should be using the new one (https://learn.microsoft.com/power-apps/maker/model-driven-apps/the-power-apps-grid-control)

**Comment by JimDaly** [comment]
@ericregnier 
Thanks for your contribution.
I brought your content in and @jasongre  and I reviewed it.
You should see it published in a few hours here: https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/events/grid-onrecordselect 

Let me know if you have any questions.

**Comment by JimDaly** [comment]
Testing something.

**Pull request closed without merging**
