### PR TITLE
Adding "known issue" note re deep expansion

### PR DESCRIPTION
**Pull request by bgribaudo**
To document a known issue, as reported in a long-running support request.

### CODE REVIEW

**Comment by JimDaly** [comment]
@bgribaudo 


Please consider the following series of requests:

### First: Deep insert Create

**Request**

```http
POST https://yourorg.api.crm.dynamics.com/api/data/v9.2/accounts HTTP/1.1
OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "name": "Sample Account",
  "primarycontactid": {
    "firstname": "John",
    "lastname": "Smith"
  },
  "opportunity_customer_accounts": [
    {
      "name": "Opportunity associated to Sample Account",
      "Opportunity_Tasks": [
        {
          "subject": "Task associated to opportunity"
        }
      ]
    }
  ]
}
```

**Response**

```http
HTTP/1.1 204 No Content
OData-Version: 4.0
OData-EntityId: https://yourorg.api.crm.dynamics.com/api/data/v9.2/accounts(226e5c0d-8e12-ed11-b83d-0022482df33a)
```

### Second: Retrieve the records created via Deep Insert

**Request**

```http
GET https://yourorg.api.crm.dynamics.com/api/data/v9.2/accounts(226e5c0d-8e12-ed11-b83d-0022482df33a)?$select=name&$expand=primarycontactid($select=firstname,lastname),opportunity_customer_accounts($select=name;$expand=Opportunity_Tasks($select=subject)) HTTP/1.1
OData-MaxVersion: 4.0
OData-Version: 4.0
```

**Response**

```http
HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal
OData-Version: 4.0

{
  "@odata.context": "https://yourorg.api.crm.dynamics.com/api/data/v9.2/$metadata#accounts(name,primarycontactid(firstname,lastname),opportunity_customer_accounts(name,Opportunity_Tasks(subject)))/$entity",
  "@odata.etag": "W/\"71457700\"",
  "name": "Sample Account",
  "accountid": "226e5c0d-8e12-ed11-b83d-0022482df33a",
  "primarycontactid": {
    "@odata.etag": "W/\"71457682\"",
    "firstname": "John",
    "lastname": "Smith",
    "contactid": "236e5c0d-8e12-ed11-b83d-0022482df33a"
  },
  "opportunity_customer_accounts": [
    {
      "@odata.etag": "W/\"71457705\"",
      "name": "Opportunity associated to Sample Account",
      "opportunityid": "246e5c0d-8e12-ed11-b83d-0022482df33a",
      "Opportunity_Tasks": []
    }
  ]
}
```

Note that the `Opportunity_Tasks` collection is an empty array.

### Third: Combine Deep insert with Prefer: return-representation

**Request**

```http
POST https://yourorg.api.crm.dynamics.com/api/data/v9.2/accounts?$select=name&$expand=primarycontactid($select=firstname,lastname),opportunity_customer_accounts($select=name;$expand=Opportunity_Tasks($select=subject)) HTTP/1.1
Prefer: return=representation
OData-MaxVersion: 4.0
OData-Version: 4.0
If-None-Match: null
Content-Type: application/json; charset=utf-8

{
  "name": "Sample Account",
  "primarycontactid": {
    "firstname": "John",
    "lastname": "Smith"
  },
  "opportunity_customer_accounts": [
    {
      "name": "Opportunity associated to Sample Account",
      "Opportunity_Tasks": [
        {
          "subject": "Task associated to opportunity"
        }
      ]
    }
  ]
}
```

**Response**

```http
HTTP/1.1 201 Created
Content-Type: application/json; odata.metadata=minimal
Preference-Applied: return=representation
OData-Version: 4.0

{
  "@odata.context": "https://yourorg.api.crm.dynamics.com/api/data/v9.2/$metadata#accounts(name,primarycontactid(firstname,lastname),opportunity_customer_accounts(name,Opportunity_Tasks(subject)))/$entity",
  "@odata.etag": "W/\"71457739\"",
  "name": "Sample Account",
  "accountid": "751a7613-8e12-ed11-b83d-0022482df33a",
  "primarycontactid": {
    "@odata.etag": "W/\"71457721\"",
    "firstname": "John",
    "lastname": "Smith",
    "contactid": "761a7613-8e12-ed11-b83d-0022482df33a"
  },
  "opportunity_customer_accounts": [
    {
      "@odata.etag": "W/\"71457744\"",
      "name": "Opportunity associated to Sample Account",
      "opportunityid": "771a7613-8e12-ed11-b83d-0022482df33a",
      "Opportunity_Tasks": []
    }
  ]
}
```
Note that the `Opportunity_Tasks` collection is an empty array here as well.

What I can see is that the data returned with a `GET` and when using `POST` with `Prefer: return-representation` is the same.
So, I don't think we can say that this is exclusive to responses using `POST`.

The repro steps above apply to the content here: [Retrieve related tables by expanding collection-valued navigation properties](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/retrieve-related-entities-query#retrieve-related-tables-by-expanding-collection-valued-navigation-properties) which states:

> If you expand on collection-valued navigation parameters to retrieve related entities for entity sets, only one level of depth is returned if there is data. Otherwise the collection will return an empty array.

Unless I'm misunderstanding, it seems that everything here is by design.
Please let me know if I've not captured the scenario correctly.

**Comment by JimDaly** [comment]
But I still see areas that could be improved in the docs.
This is Retrieve operation for a single record and the link I included above is for results from an entity set.

The content for retrieve is here [Retrieve related tables for a table by expanding navigation properties](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/retrieve-entity-using-web-api#retrieve-related-tables-for-a-table-by-expanding-navigation-properties) and it doesn't mention the limitation where 2nd level collections return empty array. The same rule applies, but it isn't called out there.

This should be called out there and a note could be added about `POST` with `Prefer: return-representation`.

**Comment by bgribaudo** [comment]
Hi @JimDaly,

Thank you for investigating this. 

> This should be called out there and a note could be added about POST with Prefer: return-representation.

Sounds good to me. What would you think of making the statement "If you expand on collection-valued navigation parameters to retrieve related entities for entity sets, only one level of depth is returned if there is data. Otherwise the collection will return an empty array." a !Note (so it stands out more) and the having it appear in all three places?

**Comment by JimDaly** [comment]
@bgribaudo
I'm pushing out some changes that I hope will fill in the gaps. Please stand by.

**Comment by JimDaly** [comment]
@bgribaudo 
Applied changes found in this commit on the public repo:

https://github.com/MicrosoftDocs/powerapps-docs/commit/e929cbea8a6f4c62267c3551e5880824f6cf521d

Notes here: 

- https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/retrieve-entity-using-web-api#retrieve-related-entities-for-an-entity-instance-by-expanding-collection-valued-navigation-properties
- https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/create-entity-web-api#create-with-data-returned

fix wording here: (properties not 'parameters')

https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/retrieve-related-entities-query#retrieve-related-records-by-expanding-collection-valued-navigation-properties

I hope that these changes help clarify what people can expect and allow you to close out that long-running support ticket.

**Comment by bgribaudo** [comment]
Thank you, @JimDaly!

**Pull request closed without merging**
