### PR TITLE
Fixed link to PowerApps homepage.

### PR DESCRIPTION
**Pull request by luboshl**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@luboshl : Thanks for your contribution! The author, @Mattp123, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@luboshl : Thanks for your contribution! The author, @Mattp123, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@luboshl : Thanks for your contribution! The author, @Mattp123, has been notified to review your proposed change.

**Comment by AFTOwen** [comment]
Thanks, @luboshl! Merging this change, so it should be live soon.

**Pull request merged**
