### PR TITLE
Using SharePointIntegration.Selected in OnVisible is not supported.

### PR DESCRIPTION
**Pull request by russgove**
Using SharePointIntegration.Selected in OnVisible is not supported.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@russgove : Thanks for your contribution! The author, @sarafankit, has been notified to review your proposed change.

**Comment by sarafankit** [comment]
@russgove - Thanks for your contribution. I have suggested a small change to what you submitted. I can do the change and submit it, but don't want to loose your contribution. (Or maybe I don't know how to keep your contribution while making that changes :( )

**Comment by russgove** [comment]
Thanks! I hadn't considered using   OnNew, OnEdit or OnView,

**Comment by PRMerger19** [comment]
@russgove : Thanks for your contribution! The author, @sarafankit, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@russgove : Thanks for your contribution! The author, @sarafankit, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@russgove : Thanks for your contribution! The author, @sarafankit, has been notified to review your proposed change.

**Comment by AFTOwen** [comment]
@sarafankit If you sign off on this PR, we can publish it. Thanks.

**Comment by sarafankit** [comment]
Thanks @russgove and @AFTOwen, the changes look good. #sign-off

**Pull request merged**
