### PR TITLE
Change of uncorrected sample code

### PR DESCRIPTION
**Pull request by nakawankuma**
Button.Enabled=>DisaplayMode

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nakawankuma : Thanks for your contribution! The author, @gregli-msft, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@nakawankuma : Thanks for your contribution! The author, @gregli-msft, has been notified to review your proposed change.

**Comment by nakawankuma** [comment]
Im so sorry.
I check context, it uncorrect true/false.
modified.

**Comment by gregli-msft** [comment]
This looks good, thanks for pointing out the old code!

One other change that needs to be made here is in the sentence before the sample code "set the button's Enabled to this formula" should be "set the button's DisplayMode property to this formula".

**Comment by gregli-msft** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@nakawankuma : Thanks for your contribution! The author, @gregli-msft, has been notified to review your proposed change.

**Pull request merged**
