### PR TITLE
Adding GDPR required info

### PR DESCRIPTION
**Pull request by davidiseminger**
Adding GDPR-required content on behalf of Miguel.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@davidiseminger : Thanks for your contribution! The author, @mllopis, has been notified to review your proposed change.

**Comment by mllopis** [comment]
#sign-off

**Comment by davidiseminger** [comment]
@ktoliver I don't see the content here going live yet. You've merged, does it require a build separately? The updates are time-sensitive, so we want to ensure they go out. So far, one day after merge, they're still not live. Thanks for your help.

**Comment by ktoliver** [comment]
Fix confirmed via email

**Pull request merged**
