### PR TITLE
Applying Organizational Service remarks to Web API, as well

### PR DESCRIPTION
**Pull request by bgribaudo**
* Adjusting so that remarks about change tracking that currently are worded to just apply to the Organizational Service apply to both that service and the Web API.
* Slight clarification tweaks.

### CODE REVIEW

**Comment by phecke** [comment]
Waiting for internal feedback.

**Comment by JimDaly** [comment]
> Does that help?

I don't know that it does. It isn't expected that people manipulate the value, and the date is only part of the token value.
The other part appears to be a version number of some kind.

But I do see that this value returns 30: 
{{webapiurl}}organizations?$select=expirechangetrackingindays

Description for the column is `Maximum number of days to keep change tracking deleted records`.
It seems to be updatable.

I'm looking to talk to the dev team owner about this.

**Comment by JimDaly** [comment]
Reached out to feature team about this again.

**Comment by bgribaudo** [comment]
Thank you!

**Comment by JimDaly** [comment]
Closing this b/c the content today now has the correct expiration day duration of 30 rather than 90.

**Pull request closed without merging**
