### PR TITLE
Defining relationships in virtual tables using Modern UI

### PR DESCRIPTION
**Pull request by kkazala**
Would you be interested in updating the https://learn.microsoft.com/en-us/power-apps/maker/data-platform/create-virtual-tables-using-connectors?

The document is describing approach using old UI, while Lookup columns (and underlying relationships) may now be easily created using Modern UI

I will be happy if you could use my suggestions.

### CODE REVIEW

**Comment by JimDaly** [comment]
@kkazala 
Thank you for your contribution. 
I'll need the feature team to review these changes.

**Comment by NHelgren** [comment]
Changes for this documentation are pending, they will incorporate the details of the newer experience soon.

**Review by JimDaly — CHANGES_REQUESTED** [review]

**Comment by JimDaly** [comment]
@kkazala 
Please stand by before applying more changes.
Seems like @NHelgren already has work in progress to refresh this topic.

**Comment by kkazala** [comment]
@JimDaly  thank you for reviewing the PR; I have no idea why these additional characters are added, seems like my VSCode Extension “improved” sth without me noticing
It’s great to hear that the product team is updating the documentation, I should have asked before opening the PR :)

**Comment by JimDaly** [comment]
@kkazala 

Very much appreciate all contributions. Please don't be discouraged.
If you see something out-of-date that you want to update, please ping us.
But since there is already some work being done to update this topic, I'm going to close this PR.

Thanks!

**Pull request closed without merging**
