### PR TITLE
Add print to list of unsupported commands

### PR DESCRIPTION
**Pull request by anshuman-ms**
Print is not supported in command designer, updating documentation

### CODE REVIEW

**Comment by anshuman-ms** [comment]
@Tapan ***@***.***>/ @Matthew ***@***.***> Can you help update this change and add Print() to the list of unsupported commands?




//Anshuman



________________________________

**Comment by Mattp123** [comment]
Handled via https://github.com/MicrosoftDocs/powerapps-docs/pull/5352

**Comment by anshuman-ms** [comment]
@Anshuman ***@***.***> – Thank you for your contribution. I re-created your PR in the private repo<https://github.com/MicrosoftDocs/powerapps-docs/pull/5352> as per our content publishing process. The change will be published live in about 4.5 hours.

In the future, please follow the guidelines below to make your changes in our private repos.

https://review.learn.microsoft.com/en-us/bacx/make-quick-edits?branch=main

Matt Peart
Power Apps content publishing

**Comment by anshuman-ms** [comment]
Awesome! Thanks Matt, this knowledge will definitely help us in the future.



//Anshuman



________________________________
From: Matthew Peart ***@***.***>
Sent: Wednesday, July 17, 2024 7:34 AM
To: Anshuman Ansu ***@***.***>; MicrosoftDocs/powerapps-docs ***@***.***>; MicrosoftDocs/powerapps-docs ***@***.***>; Tapan Maniar ***@***.***>
Cc: Author ***@***.***>; Travis Shu ***@***.***>
Subject: RE: [MicrosoftDocs/powerapps-docs] Add print to list of unsupported commands (PR #5352)


@Anshuman ***@***.***> – Thank you for your contribution. I re-created your PR in the private repo<https://github.com/MicrosoftDocs/powerapps-docs/pull/5352> as per our content publishing process. The change will be published live in about 4.5 hours.



In the future, please follow the guidelines below to make your changes in our private repos.



https://review.learn.microsoft.com/en-us/bacx/make-quick-edits?branch=main



Matt Peart

Power Apps content publishing

**Pull request closed without merging**
