### PR TITLE
Update powerapps-custom-visual.md

### PR DESCRIPTION
**Pull request by cmfinlan**
Added language around not being supported in PBIRS

### CODE REVIEW

**Comment by PRMerger19** [comment]
@cmfinlan : Thanks for your contribution! The author, @mgblythe, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@cmfinlan : Thanks for your contribution! The author, @mgblythe, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@cmfinlan : Thanks for your contribution! The author, @chmoncay, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@cmfinlan : Thanks for your contribution! The author, @chmoncay, has been notified to review your proposed change.

**Pull request merged**
