### PR TITLE
Updating to indicate that parameter aliases cannot be used in $expand

### PR DESCRIPTION
**Pull request by bgribaudo**

### CODE REVIEW

**Comment by phecke** [comment]
@JimDaly Web API related so assigning to you.

**Comment by bgribaudo** [comment]
Thank you, @JimDaly!

> I think this should work, but the fact that the error code is "code": "0x0",, and the strange nature of the error message suggests this comes from the OData Library.

Any chance that an issue can be opened internally for this to be addressed so that it does work?

**Comment by JimDaly** [comment]
> Any chance that an issue can be opened internally for this to be addressed so that it does work?

I raised this to the API team for awareness but didn't open a bug since the error comes from code we don't own.

**Comment by bgribaudo** [comment]
Thanks, @JimDaly! Hope you have a great Fourth of July!

**Pull request closed without merging**
