### PR TITLE
Fix equivalent sample for Coalesce

### PR DESCRIPTION
**Pull request by DAXaholic**
The equivalent sample for Coalesce is missing the required negation in order to show the same behavior as Coalesce.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@DAXaholic : Thanks for your contribution! The author, @gregli-msft, has been notified to review your proposed change.

**Comment by AFTOwen** [comment]
@gregli-msft Does this change look good to you?
@DAXaholic If Greg is good with it, we'll need to update your branch to reflect the most recent changes. If you can do that yourself, great. Otherwise, we'll handle it on our side. Then Greg can sign off.

**Comment by PRMerger18** [comment]
@DAXaholic : Thanks for your contribution! The author, @gregli-msft, has been notified to review your proposed change.

**Comment by AFTOwen** [comment]
@DAXaholic Looks like your fork is being updated automatically on our side to avoid merge conflicts. :-) All we need is for @gregli-msft to sign off. Thanks.

**Comment by PRMerger18** [comment]
@DAXaholic : Thanks for your contribution! The author, @gregli-msft, has been notified to review your proposed change.

**Comment by gregli-msft** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@DAXaholic : Thanks for your contribution! The author, @gregli-msft, has been notified to review your proposed change.

**Pull request merged**
