### PR TITLE
Fixing typos about XrmToolBox and FetchXML Builder

### PR DESCRIPTION
**Pull request by rappen**
We like to write correctly, right 🙂

### CODE REVIEW

**Review by JimDaly — APPROVED** [review]

**Comment by JimDaly** [comment]
I have always put XrmToolbox before any of the plug-ins built for it since people need to know what XrmToolbox first. But I'm fine with this change.

**Comment by rappen** [comment]
Thanks!
The important thing is, though, that XrmToolBox shall have a capital B, and the format of FetchXML Builder is what is written everywhere in my docs, blogs, etc.
For more info, read https://x.com/rappen/status/951009993989459969 (as I wrote in January 2018, and still very valid 😉)

**Comment by JimDaly** [comment]
Right. You are fighting everyone who [knows how to spell the word toolbox](https://www.merriam-webster.com/dictionary/toolbox). IDK how much value there is in having your alternative spelling for your brand, but it seems this will be a perpetual issue.

Happy to get your contributions Jonas.

**Comment by rappen** [comment]
XrmToolBox is not a word - it's a brand. 😉
And btw - it's not me who chose those upper/lower cases; that's Tanguy's fault 😁

**Comment by JimDaly** [comment]
[like]  Jim Daly reacted to your message:
________________________________

**Pull request merged**
